- Gemfile.lock
- index.md
- pages/architecture.md
- pages/existing_instrumentations.md
- pages/instrumenting.md
- pages/span_receivers.md
Changed flow of architecture page and added transition text. 
added link in Architecture page to Span Receivers page (I hope!)
minor updates throughout
-simplified language
> Final edits

- _data/existing_instrumentations.yml
As a result of [this PR](https://github.com/openzipkin/zipkin-js/pull/20), adding [restify](http://restify.com/) as a supported framework.
> Adding restify to supported instrumentations

- _data/existing_instrumentations.yml
Even though `zipkin-go-opentracing` in combination with `Go kit` is a really good option (I highly recommend going this route) the tracing library itself is fully `OpenTracing API` compatible and can easily be used in other frameworks or roll your own environments. closes #42
> list zipkin-go-opentracing as stand-alone option

- _data/existing_instrumentations.yml
This fixes the yaml syntax error I introduced when updating the zipkin-go-opentracing listing.
> fix yml error in existing instrumentations data file

- pages/instrumenting.md
Over the last year I've noticed a problem where instrumentors accidentally send too much data.
For example, things bubble up as frame size exceeded (like 64MiB) etc. While a lot of systems can
handle loads, there's often an error when something like this is going on. For example, it might be
someone replicating the entire http message in a trace, or storing all headers, etc.
At the moment, only Finagle's tracer bounds the size of a span before placing it on the transport. For
example, it makes sure a scribe message flushes at 5MiB. I've noticed others mention they alert
when their instrumentation report very large spans.
Getting to transport errors is the worst place to help folks. I figured adding some docs here might
obviate this sort of problem, or at least give folks a good chance to …
> Adds advice about bounding spans

- pages/instrumenting.md
This comes up a lot, and I had notes. Here's an attempt to collect them all into one place.
See https://github.com/openzipkin/zipkin/issues/1280
See #40
> Adds overdue information about setting timestamps and duration

- _data/existing_instrumentations.yml
swagger_zipkin is not actually pyramid specific. Its dependency is now on py_zipkin :)
> Remove mention of pyramid from swagger_zipkin

- pages/architecture.md
As it isn't rendered correctly on the website.
<details>
</details>
> Fixes bullet list of Zipkin components

- pages/instrumenting.md
I made some insights when collaborating with @paolochiodi. This change represents the simplest pseudocode I can think of for how to understand when you should set Span.timestamp and duration. 
https://github.com/paolochiodi/zipkin-simple/pull/2#issuecomment-250770128
cc @basvanbeek
> Adds simplest example of set Span.timestamp and duration

- _data/community_instrumentations.yml
We created a new library, and it has already been using in our production environment for a while.
It works fine to us.
> add flask_zipkin into community_instrumentations.yml

- pages/architecture.md
- public/css/zipkin.css
Adds a sequence diagram that shows instrumentation do things in band and out-of-band
See #68
> Adds diagram showing trace instrumentation's role in architecture

- pages/instrumenting.md
The instrumenting doc needs a significant overhaul. This fixes some
blatant issues regarding the length of identifiers.
> Fixes some out-of-date references to trace IDs being 64-bit

- _data/community_instrumentations.yml
Molten is application transparent php extension, user do not change anything, just install the molten extension, so they can see in zipkin server. 
please see https://github.com/chuan-yun/Molten#quickstart, you can see tracing info in zipkin server.
> add php  instrumentation "Molten"

- quickstart.sh
As discussed in #93. Example session:
```console
$ ./quickstart.sh -h
./quickstart.sh
Downloads the latest version of the Zipkin Server executable jar
./quickstart.sh GROUP:ARTIFACT:CLASSIFIER TARGET
Downloads the latest version of GROUP:ARTIFACT with classifier "CLASSIFIER"
to path "TARGET" on the local file system. For example:
./quickstart.sh io.zipkin.java:zipkin-autoconfigure-collector-kafka10:module kafka10.jar
downloads the latest version of the artifact with group "io.zipkin.java",
artifact id "zipkin-autoconfigure-collector-kafka10", and classifier "module"
to PWD/kafka10.jar
$ ./quickstart.sh
Thank you for trying OpenZipkin!
This installer is provided as a quick-start helper, so you can try Zipkin out
without a lengthy installation process.
Fetching version number of latest …
```
> Extend quickstart.sh to download any artifact

- _data/openzipkin_instrumentations.yml
zipkin-go is ready for usage now. add to list of officially supported tracers
> Adds zipkin-go to list of official libraries

- generate_thrift_v1_docs/generate.sh
- public/thrift/v1/index.html
- public/thrift/v1/zipkinCore.html
- public/thrift/v1/zipkinDependencies.html
This PR changes the doc generator script to use Docker images for all
the weird utilities. That includes Thrift itself, so now we have
explicit control over which version of Thrift is used to generate the
docs. I opted for the latest one, which seems to replace `blockquote`s
with `pre`s for long field descriptions. FWIW, I prefer the new look.
This PR _also_ regenerates the docs, as requested in https://github.com/openzipkin/zipkin-api/pull/43#issuecomment-369061321.
It also downgrades `tidy` by 5 patch versions. Whatevs.
> By the power of Docker, I compel you!

- _data/community_instrumentations.yml
- _data/openzipkin_instrumentations.yml
Demoting zipkin-go-opentracing to community contrib support level as we have much better idiomatic Zipkin instrumentation for Go through the zipkin-go project.
> move zipkin-go-opentracing to community contrib

- quickstart.sh
Had to change the API used here, since originally the script had no way of knowing which Bintray repo the artifact is published into. For example, the Maven artifact `io.zipkin.aws:zipkin-autoconfigure-collector-kinesis` lives in the `zipkin-aws` Bintray repo. The `/search/packages/maven` API does what we need, but can potentially return multiple matches (if the same artifact lives in multiple repositories). The added complexity is to protect against this case.
> Fix #112: quickstart is grabbing the wrong version for external modules

- quickstart.sh
... or any other environment without a full-featured terminal. For example `tput bold` exits with status 1 under `TERM=dumb`. Since `-e` is set, this aborts the full script execution.
This should fix the issue reported in https://github.com/openzipkin/openzipkin.github.io/pull/114#issuecomment-419091732. @marcingrzejszczak do you have a way of running the script in your CI env from this branch? If you could verify it fixes the issue, it'd be much appreciated.
> [quickstart.sh] Fix aborting on failed tput under CI envs

- _data/community_tracers_instrumentation.yml
Adding cppkin, a tracing client supporting both cpp and python to the community list.
> Adding cppkin to the community list.

- quickstart.sh
As discussed on https://github.com/openzipkin/openzipkin.github.io/commit/db5f7afa930e64f70511a42dbc44fc907b504f65#commitcomment-34556051
Tested by running `quickstart.sh`, seems to be doing the right thing.
> quickstart.sh: re-enable GPG verification

- quickstart.sh
It is unlikely someone will manually enter zipkin's old group ID, but
just in case.
Fixes #139
> Warns and redirects to the new group ID

- pages/extensions_choices.md
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>
Recent Jaeger v1.14 release added support for Zipkin proto support on `/api/v2/spans`
Refer to:
https://github.com/jaegertracing/jaeger/releases/tag/v1.14.0
https://github.com/jaegertracing/jaeger/pull/1695
> Update docs for Jaeger backend

- quickstart.sh
Busybox implementation of md5sum doesn't support the --check flag, instead supporting -c. This makes the Quickstart installer fail on systems like Alpine Linux.
> Fix md5sum command usage for BusyBox

- _data/community_tracers_instrumentation.yml
Hi,
Here is a Clojure library for tracing. It's Zipkin oriented but theoretically can be used with other tracing systems. Please tell me if there are any special requirements for a library to get into the list of supported tracers.
> Add a community supported tracer zipkin-clj (Clojure)

- .github/workflows/check-domain-expiry.yml
Adds daily check of zipkin.io expiry and files an issue if less than 30 days left.
> Add action to check expiry of zipkin.io

- _data/community_tracers_instrumentation.yml
Adding https://github.com/labstack/echo-contrib/tree/master/zipkintracing to community tracers instrumentations. 
cc: @jcchavezs
> adding echo zipkin tracing to community tracers instrumentations

- pages/extensions_choices.md
Since SkyWalking 9.4.0, we officially bring Zipkin UI bundled in SkyWalking v9 UI
- doc, https://skywalking.apache.org/docs/main/next/en/setup/zipkin/tracing/
- screenshot
> Update SkyWalking to add Lens UI bundled.

- quickstart.sh
This PR addresses an issue where the Zipkin-server erroneously submitted a version number (`3.0.0-rc0`) that caused failures when using `curl -sSL https://zipkin.io/quickstart.sh | bash -s`. The modification in this PR changes the version fetching logic to identify and use the last available stable version number, ensuring successful downloads and execution.
> Fix Version fetching in quick start script for Zipkin-Server

- _data/community_extensions.yml
- _data/community_tracers_instrumentation.yml
- _data/tracers_instrumentation.yml
This removes extensions and tracers that are archived or implicitly via abandonment for 4 years. If any become maintained again, they can be re-added as necessary.
Folks can add more if they like. I also added brave-cassandra as it was missing and there are a few more official ones maybe @reta can help add.
@shakuzen there's nothing here for micrometer tracing so if you like, add a follow-up PR for community supported tracers and instrumentation.
@jack-berg there's nothing here for OTEL, so if you like, you can add a follow-up PR for communit supported tracers and instrumentation, as well alternative servers as OTLP as I understand accepts zipkin format.
https://github.com/openzipkin/openzipkin.github.io/blob/master/pages/extensions_choices.md#alternative-servers
> Removes tracers and extensions not updated in 4 years

- _data/community_tracers_instrumentation.yml
> Define opentelemetry community tracer

- zipkin-helm/artifacthub-repo.yml
- zipkin-helm/index.html
The Artifacthub package https://artifacthub.io/packages/helm/zipkin/zipkin refers to `https://zipkin.io/zipkin-helm` repository, adding the `artifacthub-repo.yml` over there so it could be discovered by Artifacthub (verified locally, `http://localhost:4000/zipkin-helm/artifacthub-repo.yml` is fully accessible)
> List on Artifacthub: add initial artifacthub-repo.yml to claim repository ownership

- pages/quickstart.md
* Replace Docker Zipkin url, 👁️ pointing to [archived repo](https://github.com/openzipkin-attic/docker-zipkin) 👁️ , by the new [repo](https://github.com/openzipkin/zipkin/tree/master/docker)
* Check the URLs are valid
> doc(pages.quickstart): replace docker zipkin url
