openzipkin/openzipkin.github.io

- pages/existing_instrumentations.md
- pages/quickstart.md
- pages/span_receivers.md
corrected spelling and grammar throughout. 
existing instrumentation:
-added text to make it flow better
quick start:
-added text to give context to the information that would be presented
-ordered list to unordered list since order doesn't matter.
span receivers
- removed explanation of span receivers (not relevant to average reader)
> Edits of existing instrumentation, quick start, and span receivers

- _data/existing_instrumentations.yml
Hi guys,
Completely missed this list, fixing it. 
As a side question, I've noticed 'lc support' in notes for some libs. Is there any related docs, or I should just start with [corresponding ticket](https://github.com/openzipkin/zipkin/pull/821)?
> Add akka-tracing to existing instrumentations list

- pages/instrumenting.md
> Change ss to sr

- _data/existing_instrumentations.yml
Resolves https://github.com/Yelp/py_zipkin/issues/2
> Add py_zipkin and swagger_zipkin tracers to existing_instrumentations

- pages/instrumenting.md
same question was raised by @fedj and @paolochiodi basically.. why should I?
This is an attempt to help folks make the right decisions. While adding timestamp
and duration is trivial, the reason why shouldn't be "cause you should" :)
> Adds more insight into why following timestamp practice helps

- pages/instrumenting.md
Often it is the case that people ask questions we already have answers to. For starters, let's make the thrift doc known!
See https://github.com/openzipkin/zipkin-api/issues/21
> Add link to data structure details

- pages/architecture.md
Minor fixes to Architecture page:
- updated transport section
- more consistent line wrap around 80chars
- fixed minor typos
> minor fixes to Architecture page

- _data/community_instrumentations.yml
https://github.com/flier/zipkin-cpp is a full featured c/c++ library maintained by @flier
> Adds zipkin-cpp

- pages/instrumenting.md
> Fix misspelled word

- _data/community_instrumentations.yml
> Adds jcchavezs/zipkin

- _data/community_instrumentations.yml
As discussed in gitter here is my PR that adds https://github.com/aio-libs/aiozipkin library to the list
> Adds aiozipkin to the list of libraries

- .circleci/config.yml
- Gemfile.lock
- pages/community.md
- pages/span_receivers.md
Content about logos can go here. Here are some references:
http://netty.io/community.html
https://www.elastic.co/community
See #91
>  Adds community page

- quickstart.sh
* Made variables `local`, to prevent functions from overwriting values
of each other
* Made downloaded jar filename shorter, it's just `zipkin.jar` now
* Told `curl` to follow redirects (fixing downloads when BinTray
redirects to a CDN)
* Clean up `.md5`, `.asc`, `.md5.asc` after successful runs (but not
after failed ones)
* Add a note to optionally trust the BinTray GPG key after importing it
* Add note for proceeding manually if the script fails
* Fix verification of GPG signature of MD5 checksum
```
Thank you for trying OpenZipkin!
This installer is provided as a quick-start helper, so you can try Zipkin out
without a lengthy installation process.
Fetching version number of latest Zipkin release...
Downloading executable jar for Zipkin 2.4.0...
Verifying checksum...
zipkin.jar: OK …
```
> Various improvements to quickstart.sh

- pages/architecture.md
It also adds a header for the components section
> Removes the link to a page that no longer exists

- _data/community_instrumentations.yml
This PR adds zipkin-opentracing-php
> Adds zipkin-opentracing-php

- _data/community_instrumentations.yml
An integration with [VueJS](https://vuejs.org/) framework that helps to instrument outgoing HTTP requests.
> Adds another integration with Javascript framework

- _data/community_instrumentations.yml
> correct path for zipkin-go-opentracing

- _data/community_instrumentations.yml
> Add NodeJS MySQL instrumentation to `community_instrumentation`

- _data/community_transport_integrations.yml
- _data/openzipkin_transport_integrations.yml
- _data/transport_integrations.yml
- pages/existing_transport_integrations.md
Transport integration page added.
- feedbacks plz.
- As far as I know, I have included relevant libraries. If you have anything to add, please let me know it's URL links to refer to.
- English is not my first language. Please help me to be fluent in the content.
> Add transport integration page.

- pages/extensions_choices.md
I will add a note about Kafka sometime later this year.
> Add pitchfork to extension choices

- _data/community_extensions.yml
- _data/community_tracers_instrumentation.yml
Links to:
- https://github.com/jeqo/zipkin-storage-kafka 
- https://github.com/sysco-middleware/kafka-interceptor-zipkin
> Kafka interceptor and storage

- _data/community_tracers_instrumentation.yml
This PR adds some of the libraries I have been working on.
Ping @openzipkin/core
> chore: adds community libraries.

- .circleci/config.yml
This PR attempts to fix the swagger file update by forcing a remote pull of the swagger files submodule.
Ping @abesto @adriancole
> fix: attempt to fix the swagger file update.

- pages/data_model.md
> chore: updates data model to V2 JSON.

- pages/instrumenting.md
This was never implememented consistently. Also, this document is really
out-of-date. Less content is less to convert.
See https://github.com/openzipkin/brave/pull/1169
> Removes one-way tracing example

- _data/community_tracers_instrumentation.yml
This PR updates the zipkin-go-sql package as we moved from my personal repo to contrib.
> chore(zipkin-go-sql): updates zipkin-go-sql accordingly.
